export const FETCH_COMMISSION_REQUEST = "FETCH_COMMISSION_REQUEST";
export const FETCH_COMMISSION_SUCCESS = "FETCH_COMMISSION_SUCCESS";
export const FETCH_COMMISSION_FAIL = "FETCH_COMMISSION_FAIL";

export const CREATE_COMMISSION_REQUEST = "CREATE_COMMISSION_REQUEST";
export const CREATE_COMMISSION_SUCCESS = "CREATE_COMMISSION_SUCCESS";
export const CREATE_COMMISSION_FAIL = "CREATE_COMMISSION_FAIL";

export const COMMISSION_DETAIL_REQUEST = "COMMISSION_DETAIL_REQUEST";
export const COMMISSION_DETAIL_SUCCESS = "COMMISSION_DETAIL_SUCCESS";
export const COMMISSION_DETAIL_FAIL = "COMMISSION_DETAIL_FAIL";

export const COMMISSION_UPDATE_REQUEST = "COMMISSION_UPDATE_REQUEST";
export const COMMISSION_UPDATE_SUCCESS = "COMMISSION_UPDATE_SUCCESS";
export const COMMISSION_UPDATE_FAIL = "COMMISSION_UPDATE_FAIL";

export const RESET_NEW = "RESET_NEW";
export const RESET_DELETE = "RESET_DELETE";
export const RESET_DETAILS = "RESET_DETAILS";
export const RESET_UPDATE = "RESET_UPDATE";

export const CLEAR_ERROR = "CLEAR_ERROR";