export const CREATE_JOURNEY_REQUEST = "CREATE_JOURNEY_REQUEST";
export const CREATE_JOURNEY_SUCCESS = "CREATE_JOURNEY_SUCCESS";
export const CREATE_JOURNEY_FAIL = "CREATE_JOURNEY_FAIL";

export const FETCH_USER_JOURNEY_REQUEST = "FETCH_USER_JOURNEY_REQUEST";
export const FETCH_USER_JOURNEY_SUCCESS = "FETCH_USER_JOURNEY_SUCCESS";
export const FETCH_USER_JOURNEY_FAIL = "FETCH_USER_JOURNEY_FAIL";

export const PLACE_USER_JOURNEY_REQUEST = "PLACE_USER_JOURNEY_REQUEST";
export const PLACE_USER_JOURNEY_SUCCESS = "PLACE_USER_JOURNEY_SUCCESS";
export const PLACE_USER_JOURNEY_FAIL = "PLACE_USER_JOURNEY_FAIL";

export const SUBMIT_USER_JOURNEY_REQUEST = "SUBMIT_USER_JOURNEY_REQUEST";
export const SUBMIT_USER_JOURNEY_SUCCESS = "SUBMIT_USER_JOURNEY_SUCCESS";
export const SUBMIT_USER_JOURNEY_FAIL = "SUBMIT_USER_JOURNEY_FAIL";

export const USER_JOURNEY_BY_ID_REQUEST = "USER_JOURNEY_BY_ID_REQUEST";
export const USER_JOURNEY_BY_ID_SUCCESS = "USER_JOURNEY_BY_ID_SUCCESS";
export const USER_JOURNEY_BY_ID_FAIL = "USER_JOURNEY_BY_ID_FAIL";

export const GET_JOURNEY_HISTORY_REQUEST = "GET_JOURNEY_HISTORY_REQUEST";
export const GET_JOURNEY_HISTORY_SUCCESS = "GET_JOURNEY_HISTORY_SUCCESS";
export const GET_JOURNEY_HISTORY_FAIL = "GET_JOURNEY_HISTORY_FAIL";

export const USER_JOURNEY_HISTORY_BY_ID_REQUEST = "USER_JOURNEY_HISTORY_BY_ID_REQUEST";
export const USER_JOURNEY_HISTORY_BY_ID_SUCCESS = "USER_JOURNEY_HISTORY_BY_ID_SUCCESS";
export const USER_JOURNEY_HISTORY_BY_ID_FAIL = "USER_JOURNEY_HISTORY_BY_ID_FAIL";

export const CREATE_CUSTOM_JOURNEY_REQUEST = "CREATE_CUSTOM_JOURNEY_REQUEST";
export const CREATE_CUSTOM_JOURNEY_SUCCESS = "CREATE_CUSTOM_JOURNEY_SUCCESS";
export const CREATE_CUSTOM_JOURNEY_FAIL = "CREATE_CUSTOM_JOURNEY_FAIL";

export const GET_ALL_CUSTOM_JOURNEY_REQUEST = "GET_ALL_CUSTOM_JOURNEY_REQUEST";
export const GET_ALL_CUSTOM_JOURNEY_SUCCESS = "GET_ALL_CUSTOM_JOURNEY_SUCCESS";
export const GET_ALL_CUSTOM_JOURNEY_FAIL = "GET_ALL_CUSTOM_JOURNEY_FAIL";

export const RESET_JOURNEY_REQUEST = "RESET_JOURNEY_REQUEST";
export const RESET_JOURNEY_SUCCESS = "RESET_JOURNEY_SUCCESS";
export const RESET_JOURNEY_FAIL = "RESET_JOURNEY_FAIL";

export const GET_CUSTOM_JOURNEY_BY_ID_REQUEST = "GET_CUSTOM_JOURNEY_BY_ID_REQUEST";
export const GET_CUSTOM_JOURNEY_BY_ID_SUCCESS = "GET_CUSTOM_JOURNEY_BY_ID_SUCCESS";
export const GET_CUSTOM_JOURNEY_BY_ID_FAIL = "GET_CUSTOM_JOURNEY_BY_ID_FAIL";

export const UPDATE_CUSTOM_JOURNEY_REQUEST = "UPDATE_CUSTOM_JOURNEY_REQUEST";
export const UPDATE_CUSTOM_JOURNEY_SUCCESS = "UPDATE_CUSTOM_JOURNEY_SUCCESS";
export const UPDATE_CUSTOM_JOURNEY_FAIL = "UPDATE_CUSTOM_JOURNEY_FAIL";

export const GET_USER_JOURNEY_BY_ID_REQUEST = "GET_USER_JOURNEY_BY_ID_REQUEST";
export const GET_USER_JOURNEY_BY_ID_SUCCESS = "GET_USER_JOURNEY_BY_ID_SUCCESS";
export const GET_USER_JOURNEY_BY_ID_FAIL = "GET_USER_JOURNEY_BY_ID_FAIL";

export const UPDATE_USER_JOUNREY_REQUEST = "UPDATE_USER_JOUNREY_REQUEST";
export const UPDATE_USER_JOUNREY_SUCCESS = "UPDATE_USER_JOUNREY_SUCCESS";
export const UPDATE_USER_JOUNREY_FAIL = "UPDATE_USER_JOUNREY_FAIL";

export const RESET_NEW = "RESET_NEW";
export const RESET_DETAILS = "RESET_DETAILS";
export const RESET_UPDATE = "RESET_UPDATE";

export const CLEAR_ERROR = "CLEAR_ERROR";