export const GET_NOTIFICATION_BY_ID_REQUEST = "GET_NOTIFICATION_BY_ID_REQUEST";
export const GET_NOTIFICATION_BY_ID_SUCCESS = "GET_NOTIFICATION_BY_ID_SUCCESS";
export const GET_NOTIFICATION_BY_ID_FAIL = "GET_NOTIFICATION_BY_ID_FAIL";

export const GET_ALL_NOTIFICATION_BY_ID_REQUEST = "GET_ALL_NOTIFICATION_BY_ID_REQUEST";
export const GET_ALL_NOTIFICATION_BY_ID_SUCCESS = "GET_ALL_NOTIFICATION_BY_ID_SUCCESS";
export const GET_ALL_NOTIFICATION_BY_ID_FAIL = "GET_ALL_NOTIFICATION_BY_ID_FAIL";

export const UPDATE_NOTIFICATION_REQUEST = "UPDATE_NOTIFICATION_REQUEST";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_FAIL = "UPDATE_NOTIFICATION_FAIL";

export const RESET_NEW = "RESET_NEW";
export const RESET_DETAILS = "RESET_DETAILS";
export const RESET_UPDATE = "RESET_UPDATE";

export const CLEAR_ERROR = "CLEAR_ERROR";