export const FETCH_USER_WALLET_REQUEST = "FETCH_USER_WALLET_REQUEST";
export const FETCH_USER_WALLET_SUCCESS = "FETCH_USER_WALLET_SUCCESS";
export const FETCH_USER_WALLET_FAIL = "FETCH_USER_WALLET_FAIL";

export const FETCH_USER_WALLET_BY_ID_REQUEST = "FETCH_USER_WALLET_BY_ID_REQUEST";
export const FETCH_USER_WALLET_BY_ID_SUCCESS = "FETCH_USER_WALLET_BY_ID_SUCCESS";
export const FETCH_USER_WALLET_BY_ID_FAIL = "FETCH_USER_WALLET_BY_ID_FAIL";

export const CHARGE_WALLET_REQUEST = "CHARGE_WALLET_REQUEST";
export const CHARGE_WALLET_SUCCESS = "CHARGE_WALLET_SUCCESS";
export const CHARGE_WALLET_FAIL = "CHARGE_WALLET_FAIL";

export const SAVE_WALLET_ADDRESS_REQUEST = "SAVE_WALLET_ADDRESS_REQUEST";
export const SAVE_WALLET_ADDRESS_SUCCESS = "SAVE_WALLET_ADDRESS_SUCCESS";
export const SAVE_WALLET_ADDRESS_FAIL = "SAVE_WALLET_ADDRESS_FAIL";

export const SAVE_WALLET_PIN_REQUEST = "SAVE_WALLET_PIN_REQUEST";
export const SAVE_WALLET_PIN_SUCCESS = "SAVE_WALLET_PIN_SUCCESS";
export const SAVE_WALLET_PIN_FAIL = "SAVE_WALLET_PIN_FAIL";

export const EDIT_WALLET_REQUEST = "EDIT_WALLET_REQUEST";
export const EDIT_WALLET_SUCCESS = "EDIT_WALLET_SUCCESS";
export const EDIT_WALLET_FAIL = "EDIT_WALLET_FAIL";

export const GET_TRANSACTION_REQUEST = "GET_TRANSACTION_REQUEST";
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS";
export const GET_TRANSACTION_FAIL = "GET_TRANSACTION_FAIL";

export const GET_TRANSACTION_HISTORY_REQUEST = "GET_TRANSACTION_HISTORY_REQUEST";
export const GET_TRANSACTION_HISTORY_SUCCESS = "GET_TRANSACTION_HISTORY_SUCCESS";
export const GET_TRANSACTION_HISTORY_FAIL = "GET_TRANSACTION_HISTORY_FAIL";

export const RESET_NEW = "RESET_NEW";
export const RESET_DETAIL = "RESET_DETAIL";
export const RESET_UPDATE = "RESET_UPDATE";

export const CLEAR_ERROR = "CLEAR_ERROR";