export const USER_WITHDRAWAL_REQUEST = "USER_WITHDRAWAL_REQUEST";
export const USER_WITHDRAWAL_SUCCESS = "USER_WITHDRAWAL_SUCCESS";
export const USER_WITHDRAWAL_FAIL = "USER_WITHDRAWAL_FAIL";

export const WITHDRAWAL_REQUEST = "WITHDRAWAL_REQUEST";
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_FAIL = "WITHDRAWAL_FAIL";

export const WITHDRAWAL_ANSWER_REQUEST = "WITHDRAWAL_ANSWER_REQUEST";
export const WITHDRAWAL_ANSWER_SUCCESS = "WITHDRAWAL_ANSWER_SUCCESS";
export const WITHDRAWAL_ANSWER_FAIL = "WITHDRAWAL_ANSWER_FAIL";

export const RESET_NEW = "RESET_NEW";
export const RESET_DETAIL = "RESET_DETAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";